results_dir: /results/ours_cache128_inflight1_1s
output_dir: /media/ours_cache128_inflight1_1s

mpd_template: /app/src/templates/mpd_template.xml
representation_template: /app/src/templates/representation_template.xml
gop_size: 30
total_frames: 2400
timescale: 30
baseline: False

cache_size: 128 # 10 [MB] is roughly 15 objects / 0 means no cache
prefetch_depth: 1

# Which GPU's to use
gpu_plan:
  2: 4

sequences:
  loot:
    data_path: "/media/encoded_80s/{}/loot"
    base_config: "5"
    offered_configs:
    - "4"
    - "3"
    - "2"
    - "1"
  redandblack:
    data_path: "/media/encoded_80s/{}/redandblack"
    base_config: "5"
    offered_configs:
    - "4"
    - "3"
    - "2"
    - "1"
  longdress:
    data_path: "/media/encoded_80s/{}/longdress"
    base_config: "5"
    offered_configs:
    - "4"
    - "3"
    - "2"
    - "1"
  soldier:
    data_path: "/media/encoded_80s/{}/soldier"
    base_config: "5"
    offered_configs:
    - "4"
    - "3"
    - "2"
    - "1"

# Settings for offered Rates by the transcoder
transcoder:
  "1":
    geoQP: 32
    attQP: 42
    preset: "p2"
    cuda: true
    bw_estimate_factor: 0.32
  "2":
    geoQP: 28
    attQP: 37
    preset: "p2"
    cuda: true
    bw_estimate_factor: 0.48
  "3":
    geoQP: 24
    attQP: 32
    preset: "p2"
    cuda: true
    bw_estimate_factor: 0.67
  "4":
    geoQP: 20
    attQP: 27
    preset: "p2"
    cuda: true
    bw_estimate_factor: 0.9